In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

tf.random.set_seed(42)

import random
random.seed(42)
import numpy as np
np.random.seed(42)

2022-08-31 01:47:27.113879: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [2]:
from pandas_ods_reader import read_ods

df = read_ods('Biogas data.ods', 'plant1')

In [3]:
num = df._get_numeric_data()

In [4]:
x = num.iloc[:, :]

y = num.iloc[:, -1]

In [5]:
from sklearn.preprocessing import StandardScaler

scaler_vae = StandardScaler()

x_full_scaled = scaler_vae.fit_transform(x)

In [6]:
print(x_full_scaled)

[[-1.38240012 -0.90798538 -0.90900974  1.45070271  0.31622777 -0.23325717]
 [-0.31992351  0.51000078  0.51131798  1.89299012  0.31622777 -0.25700507]
 [-1.26434716 -0.84366537 -0.84321799  1.89299012  0.31622777 -0.15937481]
 [ 0.27771958  0.35176828  0.35264376  0.87572907 -1.26491106  0.29447399]
 [ 0.24082803 -0.54820918 -0.54909018 -0.4953619  -0.47434165  0.81956649]
 [ 0.5212038   0.30564283  0.30620253  0.07961173 -0.47434165  3.0993651 ]
 [ 0.61712183  0.50054329  0.49970767  0.52189914  0.31622777  3.02548274]
 [-1.21269899 -1.10845005 -1.10638498  0.43344166  0.31622777  0.72985219]
 [ 2.10016209 -1.61220308 -1.61336844 -3.41445881  0.31622777 -0.07493782]
 [ 2.68304856  2.48904564  2.48894049 -0.22998945  1.10679718 -0.32297147]
 [ 0.68352662  1.80070272  1.8000622   0.65458537  0.31622777 -0.84278666]
 [-1.02824125 -0.98227494 -0.98254169 -0.18576071  1.10679718 -0.67655135]
 [ 0.81633619  1.14967663  1.14988494 -0.45113316  1.8973666  -0.79001355]
 [-1.10940265 -0.67365974

# Variational Autoencoder

In [7]:
vae_mft = keras.models.load_model('vae.tf')
history = vae_mft.fit(x_full_scaled, x_full_scaled, epochs=500)
 


2022-08-31 01:47:29.029666: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-08-31 01:47:29.029860: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-08-31 01:47:29.029868: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-31 01:47:29.029881: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-GM3F9HH): /proc/driver/nvidia/version does not exist
2022-08-31 01:47:29.030020: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild T

Epoch 1/500
1/1 [==============================] - 1s 770ms/step - loss: 1.0067 - mean_squared_error: 1.0018
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 1.0302 - mean_squared_error: 1.0082
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 0.9886 - mean_squared_error: 0.9829
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 0.9658 - mean_squared_error: 0.9527
Epoch 5/500
1/1 [==============================] - 0s 4ms/step - loss: 0.8484 - mean_squared_error: 0.8208
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6572 - mean_squared_error: 0.6093
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6417 - mean_squared_error: 0.5614
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5518 - mean_squared_error: 0.5045
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5082 - mean_squared_error: 0.4265
Epoch 10/500
1/1 [=================

1/1 [==============================] - 0s 3ms/step - loss: 0.0860 - mean_squared_error: 0.0622
Epoch 152/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1285 - mean_squared_error: 0.1026
Epoch 153/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1062 - mean_squared_error: 0.0813
Epoch 154/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0927 - mean_squared_error: 0.0682
Epoch 155/500
1/1 [==============================] - 0s 2ms/step - loss: 0.1115 - mean_squared_error: 0.0870
Epoch 156/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0999 - mean_squared_error: 0.0727
Epoch 157/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1147 - mean_squared_error: 0.0829
Epoch 158/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1336 - mean_squared_error: 0.1029
Epoch 159/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1074 - mean_squared_error: 0.0752
Epoch 160/500
1/1 [==============

1/1 [==============================] - 0s 3ms/step - loss: 0.1002 - mean_squared_error: 0.0759
Epoch 302/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0749 - mean_squared_error: 0.0526
Epoch 303/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0850 - mean_squared_error: 0.0611
Epoch 304/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1196 - mean_squared_error: 0.0910
Epoch 305/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0835 - mean_squared_error: 0.0546
Epoch 306/500
1/1 [==============================] - 0s 4ms/step - loss: 0.1423 - mean_squared_error: 0.1085
Epoch 307/500
1/1 [==============================] - 0s 2ms/step - loss: 0.0762 - mean_squared_error: 0.0474
Epoch 308/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0893 - mean_squared_error: 0.0602
Epoch 309/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1255 - mean_squared_error: 0.0969
Epoch 310/500
1/1 [==============

1/1 [==============================] - 0s 3ms/step - loss: 0.0733 - mean_squared_error: 0.0377
Epoch 452/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0925 - mean_squared_error: 0.0578
Epoch 453/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0836 - mean_squared_error: 0.0515
Epoch 454/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0710 - mean_squared_error: 0.0409
Epoch 455/500
1/1 [==============================] - 0s 4ms/step - loss: 0.0999 - mean_squared_error: 0.0666
Epoch 456/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0666 - mean_squared_error: 0.0427
Epoch 457/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1153 - mean_squared_error: 0.0829
Epoch 458/500
1/1 [==============================] - 0s 4ms/step - loss: 0.0845 - mean_squared_error: 0.0565
Epoch 459/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0676 - mean_squared_error: 0.0403
Epoch 460/500
1/1 [==============

In [8]:
sample_size = x_full_scaled.shape[:][1]

sample_number = 250

x_simulated = np.empty((sample_number,sample_size))
 
for i in range(sample_number):
    x_simulated[i] = vae_mft.predict(x_full_scaled[[random.randrange(x_full_scaled.shape[0])]])

    
'''import matplotlib.pyplot as plt

plt.figure(figsize=(20,5))
plt.plot(x_full_scaled.flatten(), label='x real data')
plt.plot(x_simulated.flatten(), label='x simulated data')
plt.legend(loc='upper left')
plt.show()'''

"import matplotlib.pyplot as plt\n\nplt.figure(figsize=(20,5))\nplt.plot(x_full_scaled.flatten(), label='x real data')\nplt.plot(x_simulated.flatten(), label='x simulated data')\nplt.legend(loc='upper left')\nplt.show()"

In [9]:
x_full = np.concatenate([x_full_scaled, x_simulated])

In [10]:
print(x_full.shape)

(275, 6)


In [11]:
rev_x = scaler_vae.inverse_transform(x_full)
print(rev_x)

[[3.94000000e+02 3.12323800e+04 8.36000000e-01 4.92000000e+01
  4.80000000e+00 6.62000000e+02]
 [5.38000000e+02 4.49122400e+04 1.20300000e+00 5.02000000e+01
  4.80000000e+00 6.53000000e+02]
 [4.10000000e+02 3.18529000e+04 8.53000000e-01 5.02000000e+01
  4.80000000e+00 6.90000000e+02]
 ...
 [6.16546199e+02 4.62610815e+04 1.23224426e+00 4.75956434e+01
  4.66610165e+00 7.34983362e+02]
 [4.22650901e+02 2.92874817e+04 7.87850286e-01 4.71103062e+01
  4.75729382e+00 9.88115176e+02]
 [4.17498297e+02 2.90851290e+04 7.81329126e-01 4.71488332e+01
  4.76200208e+00 1.01046547e+03]]


In [12]:
x = rev_x[:, 0:-1]

y = rev_x[:, -1]

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)



In [14]:
scaler_x = StandardScaler()
x_train_scaled = scaler_x.fit_transform(x_train)
#x_valid_scaled = scaler_x.transform(x_valid)
x_test = scaler_x.transform(x_test)

In [15]:
scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1,1))
#y_valid_scaled = scaler_y.transform(y_valid.reshape(-1,1))
y_test = scaler_y.transform(y_test.reshape(-1,1))

#y_train_scaled = y_train
#y_valid_scaled = y_valid
#y_test = y_test


In [16]:
def r2_score(y_true, y_pred):
    SS_res = keras.backend.sum(keras.backend.square(y_true - y_pred))
    SS_tot = keras.backend.sum(keras.backend.square(y_true - keras.backend.mean(y_true)))
    return (1 - SS_res / (SS_tot + keras.backend.epsilon()))

# Training

In [19]:
import pandas as pd
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from sklearn.metrics import r2_score
from tensorflow.keras import backend as K
from matplotlib import pyplot

# Cross-Validate
kf = KFold(5, shuffle=True, random_state=42) # Use for KFold classification
oos_y = []
oos_pred = []

fold = 0
for train, valid in kf.split(x_train_scaled):
    K.clear_session()
    fold+=1
    print(f"Fold #{fold}")
        
    x_train = x_train_scaled[train]
    y_train = y_train_scaled[train]
    x_valid = x_train_scaled[valid]
    y_valid = y_train_scaled[valid]
    
    if fold == 1:
        model = keras.models.Sequential([
        keras.layers.Dense(24, activation="relu", input_shape=x_train.shape[1:]),
        keras.layers.Dense(28, activation="relu"),
        keras.layers.Dense(1)])
        optimizer = tf.keras.optimizers.SGD(learning_rate=0.1,
                                        momentum=0.9,
                                        nesterov=True)


        model.compile(loss="mse", optimizer=optimizer)

        model.fit(x_train, y_train, epochs = 150, validation_data=(x_valid, y_valid), verbose=0)
        pred = model.predict(x_valid)

        oos_y.append(scaler_y.inverse_transform(y_valid))
        oos_pred.append(scaler_y.inverse_transform(pred))    

        # Measure this fold's RMSE
        print('training',
              np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train))),
             r2_score(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train)))
        
        
        score = np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(pred),
                                                   scaler_y.inverse_transform(y_valid)))
        r2 = r2_score(pred,y_valid)
        print(f"Fold score (RMSE): {score}", 'r2 =', r2)
        
                        
        r2 = r2_score(model.predict(x_test), y_test)
        print('model vs holdout :',
             'rmse', np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_test)),
                                                 scaler_y.inverse_transform(y_test))),
             'r2 =', r2)
        
        model.save('NN_Kfold_1.h5')
    
    elif fold == 2:
        model = keras.models.Sequential([
        keras.layers.Dense(112, activation="relu", input_shape=x_train.shape[1:]),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(32, activation="relu"),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(1)])


        optimizer = tf.keras.optimizers.SGD(learning_rate=0.1,
                                        momentum=0.9,
                                        nesterov=True)


        model.compile(loss="mse", optimizer=optimizer)

        model.fit(x_train, y_train, epochs = 150, validation_data=(x_valid, y_valid), verbose=0)
        pred = model.predict(x_valid)

        oos_y.append(y_valid)
        oos_pred.append(pred)    

        # Measure this fold's RMSE
        print('training',
              np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train))),
             r2_score(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train)))
        
        
        score = np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(pred),
                                                   scaler_y.inverse_transform(y_valid)))
        r2 = r2_score(pred,y_valid)
        print(f"Fold score (RMSE): {score}", 'r2 =', r2)
        
                        
        r2 = r2_score(model.predict(x_test), y_test)
        print('model vs holdout :',
             'rmse', np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_test)),
                                                 scaler_y.inverse_transform(y_test))),
             'r2 =', r2)
        
        model.save('NN_Kfold_2.h5')
    
    elif fold == 3:
        model = keras.models.Sequential([
        keras.layers.Dense(36, activation="selu", input_shape=x_train.shape[1:]),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(116, activation="relu"),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(1)])


        optimizer = tf.keras.optimizers.SGD(learning_rate=0.01,
                                    momentum=0.9,
                                    nesterov=True)


        model.compile(loss="mse", optimizer=optimizer)

        model.fit(x_train, y_train, epochs = 150, validation_data=(x_valid, y_valid), verbose=0)
        pred = model.predict(x_valid)

        oos_y.append(y_valid)
        oos_pred.append(pred)    

        # Measure this fold's RMSE
        print('training',
              np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train))),
             r2_score(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train)))
        
        
        score = np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(pred),
                                                   scaler_y.inverse_transform(y_valid)))
        r2 = r2_score(pred,y_valid)
        print(f"Fold score (RMSE): {score}", 'r2 =', r2)
        
                        
        r2 = r2_score(model.predict(x_test), y_test)
        print('model vs holdout :',
             'rmse', np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_test)),
                                                 scaler_y.inverse_transform(y_test))),
             'r2 =', r2)

        model.save('NN_Kfold_3.h5')
        
    elif fold == 4:
        model = keras.models.Sequential([
        keras.layers.Dense(12, activation="selu", input_shape=x_train.shape[1:]),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(92, activation="relu"),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(1)])


        optimizer = tf.keras.optimizers.SGD(learning_rate=0.01,
                                        momentum=0.9,
                                        nesterov=True)


        model.compile(loss="mse", optimizer=optimizer)

        model.fit(x_train, y_train, epochs = 150, validation_data=(x_valid, y_valid), verbose=0)
        pred = model.predict(x_valid)

        oos_y.append(y_valid)
        oos_pred.append(pred)    

        # Measure this fold's RMSE
        print('training',
              np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train))),
             r2_score(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train)))
        
        
        score = np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(pred),
                                                   scaler_y.inverse_transform(y_valid)))
        r2 = r2_score(pred,y_valid)
        print(f"Fold score (RMSE): {score}", 'r2 =', r2)
        
                        
        r2 = r2_score(model.predict(x_test), y_test)
        print('model vs holdout :',
             'rmse', np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_test)),
                                                 scaler_y.inverse_transform(y_test))),
             'r2 =', r2)
        
        model.save('NN_Kfold_4.h5')
    
    elif fold == 5:
        model = keras.models.Sequential([
        keras.layers.Dense(124, activation="selu", input_shape=x_train.shape[1:]),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(20, activation="sigmoid"),
        #                  kernel_regularizer=keras.regularizers.l1_l2(0.01)),
        #keras.layers.Dropout(0.2),
        keras.layers.Dense(1)])


        optimizer = tf.keras.optimizers.SGD(learning_rate=0.1,
                                        momentum=0.9,
                                        nesterov=True)


        model.compile(loss="mse", optimizer=optimizer)

        model.fit(x_train, y_train, epochs = 150, validation_data=(x_valid, y_valid), verbose=0)
        pred = model.predict(x_valid)

        oos_y.append(y_valid)
        oos_pred.append(pred)    

        # Measure this fold's RMSE
        print('training',
              np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train))),
             r2_score(scaler_y.inverse_transform(model.predict(x_train)),
                                                 scaler_y.inverse_transform(y_train)))
        
        
        score = np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(pred),
                                                   scaler_y.inverse_transform(y_valid)))
        r2 = r2_score(pred,y_valid)
        print(f"Fold score (RMSE): {score}", 'r2 =', r2)
        
                        
        r2 = r2_score(model.predict(x_test), y_test)
        print('model vs holdout :',
             'rmse', np.sqrt(metrics.mean_squared_error(scaler_y.inverse_transform(model.predict(x_test)),
                                                 scaler_y.inverse_transform(y_test))),
             'r2 =', r2)
        
        model.save('NN_Kfold_5.h5')
        



Fold #1
training 21.240027718689444 0.99630011220696
Fold score (RMSE): 173.25159433477322 r2 = 0.8575504844753694
model vs holdout : rmse 42.74493580244476 r2 = 0.9829033402292818
Fold #2
training 13.742229815760723 0.9986061742117208
Fold score (RMSE): 45.190675172364394 r2 = 0.9855543269533042
model vs holdout : rmse 54.91491527302468 r2 = 0.9691359277133272
Fold #3
training 29.051220119667185 0.9936344608537289
Fold score (RMSE): 33.84121732345011 r2 = 0.9933592624516586
model vs holdout : rmse 61.196274304276386 r2 = 0.9629901180329872
Fold #4
training 36.08514984592805 0.9913652392480466
Fold score (RMSE): 46.93994440994111 r2 = 0.9779954287873555
model vs holdout : rmse 59.654468998987426 r2 = 0.9662624951229241
Fold #5
training 35.94738401969157 0.9920895411740003
Fold score (RMSE): 70.36114732022493 r2 = 0.9233211181720988
model vs holdout : rmse 68.8018698433605 r2 = 0.9560857156581066


In [18]:
from scipy.stats import ks_2samp

import pandas as pd
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from sklearn.metrics import r2_score
from tensorflow.keras import backend as K
from matplotlib import pyplot

# Cross-Validate
kf = KFold(5, shuffle=True, random_state=42) # Use for KFold classification

y_fold_1 = None
y_fold_2 = None
y_fold_3 = None
y_fold_4 = None
y_fold_5 = None

fold = 0
for train, valid in kf.split(x_train_scaled):
    K.clear_session()
    fold+=1
        
    x_train = x_train_scaled[train]
    y_train = y_train_scaled[train]
    x_valid = x_train_scaled[valid]
    y_valid = y_train_scaled[valid]
    
    y_train = scaler_y.inverse_transform(y_train)
    
    if fold==1:
        y_fold_1 = y_train[:,0]
    
    elif fold==2:
        y_fold_2 = y_train[:,0]
    
    elif fold==3:
        y_fold_3 = y_train[:,0]
    
    elif fold==4:
        y_fold_4 = y_train[:,0]
    
    else:
        y_fold_5 = y_train[:,0]
    

print((y_fold_1.shape))
print(f'Fold 1 vs 1:', ks_2samp(y_fold_1, y_fold_1))
print(f'Fold 1 vs 2:', ks_2samp(y_fold_1, y_fold_2))
print(f'Fold 1 vs 3:', ks_2samp(y_fold_1, y_fold_3))
print(f'Fold 1 vs 4:', ks_2samp(y_fold_1, y_fold_4))
print(f'Fold 1 vs 5:', ks_2samp(y_fold_1, y_fold_5))


(176,)
Fold 1 vs 1: KstestResult(statistic=0.0, pvalue=1.0)
Fold 1 vs 2: KstestResult(statistic=0.03409090909090909, pvalue=0.9999606696007478)
Fold 1 vs 3: KstestResult(statistic=0.03409090909090909, pvalue=0.9999606696007478)
Fold 1 vs 4: KstestResult(statistic=0.045454545454545456, pvalue=0.9936378137969419)
Fold 1 vs 5: KstestResult(statistic=0.05113636363636364, pvalue=0.9761141466669034)
